name: Integraci칩n Continua con Pruebas JS

on:
  push:
    branches:
      - main

jobs:
  ci_to_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Se recomienda usar una versi칩n m치s actual de Node.js, como la 14.

      - name: Instalar dependencias
        run: npm ci
      - name: Ejecutar pruebas
        run: npm test
