name: Integración continua con Node.js

on:
  pull_request:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        node-version: 10
      - run: npm ci
      - run: npm run jest
      - run: npm run build 