pipeline:
  name: Build germanPruebas
  identifier: Build_condiza_germanPruebas_1717000474562
  projectIdentifier: prueba_dos
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1716999425464
        repoName: condiza/germanPruebas
        build: <+input>
